export { Button } from './button/Button.js';
export { Toggle } from './toggle/Toggle.js';
export { AccessibilityControls } from './accessibility/AccessibilityControls.js';
export { CorporateFooter } from './footer/CorporateFooter.js';
export { LegalDocument } from './legal/LegalDocument.js';
export { DocumentHeader } from './legal/DocumentHeader.js';
export { TableOfContents } from './legal/TableOfContents.js';
export { LegalSidebar } from './legal/LegalSidebar.js';
export { LegalBreadcrumb } from './legal/LegalBreadcrumb.js';
export { LegalPortal } from './legal/LegalPortal.js';
export { ThemeProvider, useTheme } from './theme/ThemeContext.js';
export { SunIcon, MoonIcon, SettingsIcon, CloseIcon } from './icons/index.js';
export { ThemeToggle } from './theme/ThemeToggle.js';
export { AstroToggle } from './theme/AstroToggle.js';
export { amberTheme } from './theme/amberTheme.js';
export type { Theme, BrandTheme, ColorMode, BrandColors, CompanyBranding } from './theme/types.js';
export type { ButtonProps, ButtonVariant, ButtonSize, ButtonShape } from './button/Button.js';
export type { ToggleSize } from './toggle/Toggle.js';
export type { AccessibilitySettings } from './accessibility/AccessibilityPanel.js';
export type { FooterConfig, FooterVariant, CompanyInfo, ComplianceInfo } from './footer/types.js';
export type { LegalDocumentProps, DocumentMetadata, DocumentType } from './legal/types.js';
